{% set name = "schist" %}
{% set version = "0.9.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/dawe/schist/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 88917ac92bfbeb79658d4b2780ebe9a622d60a054989b0b50d2eebb3d60ece4e

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv "

requirements:
  host:
    - python >=3.8
    - pip
    - graph-tool-base <2.60
    - joblib >=1.3.0
  run:
    - python >=3.8 
    - graph-tool-base <2.60
    - joblib >=1.3.0
    - pycairo
    - scanpy
    - numpy <2.0
    - scipy
    - pandas
    - anndata
    - mudata

test:
  imports:
    - schist

about:
  home: https://github.com/dawe/schist
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Nested Stochastic Block Models for single cell analysis'
  description: |
    schist provides an interface to graph-tool library and scanpy to 
    identify cell groups using stochastic block models.
  doc_url: https://schist.readthedocs.io/
  dev_url: https://github.com/dawe/schist

extra:
  recipe-maintainers:
    - dawe
    - leomorelli
