{% set name = "schist" %}
{% set version = "0.7.15" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/dawe/schist/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ec502ef0501a2a98e2826a30527df12be2eddb1a6e357b5904203a0bd8c68e59

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv "

requirements:
  host:
    - python >=3.8
    - pip
    - graph-tool-base >=2.40
  run:
    - python >=3.8 
    - graph-tool-base >=2.40
    - pycairo
    - scanpy
    - numpy
    - scipy
    - pandas
    - anndata

test:
  imports:
    - schist

about:
  home: https://github.com/dawe/schist
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Nested Stochastic Block Models for single cell analysis'
  description: |
    schist provides an interface to graph-tool library and scanpy to 
    identify cell groups using stochastic block models.
  doc_url: https://schist.readthedocs.io/
  dev_url: https://github.com/dawe/schist

extra:
  recipe-maintainers:
    - dawe
    - leomorelli
